# rc_platform:
#   resource: "@RCPlatformBundle/Resources/config/routing.yml"
#   prefix:   /

rc_platform:
   resource: "@RCPlatformBundle/Controller"
   type:   annotation

login:
   path: /login
   defaults:
       _controller: RCUserBundle:Security:login

login_check:
   path: /login_check

logout:
   path: /logout