<?php

namespace RC\PlatformBundle\Repository;

/**
 * SynopsisRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SynopsisRepository extends \Doctrine\ORM\EntityRepository
{
}
